### ISSUE TITLE
mitigate end tag false positive detection?

### ISSUE THREAD

**Issue by dai-shi** [devongovett/rsc-html-stream#3]
Not sure, but is it safe to assume `</body></html>` appears just once?

```diff
-       controller.enqueue(encoder.encode(buf.replace('</body></html>', '')));
+       controller.enqueue(encoder.encode(buf.replace(/<\/body><\/html>$/, '')));
```
to be a little safer?

**Comment by devongovett** [comment]
hmm not sure when there would be multiple bodies but good to be defensive I guess

**Comment by dai-shi** [comment]
yeah, maybe it would never happen with the output from React streaming.

**Comment by dai-shi** [comment]
if `.endsWith('</body></html>')` then `.slice(0, -'</body></html>'.length)`
might be faster, not only safer.
But, it's up to you.

**Comment by dai-shi** [comment]
Re: 603012a

```diff
- controller.enqueue(encoder.encode('</body></html>'));
+ controller.enqueue(encoder.encode(trailer));
```
