### ISSUE TITLE
Non-Node.js env

### ISSUE THREAD

**Issue by dai-shi** [devongovett/rsc-html-stream#4]
Our use case doesn't depend on Node.js.

https://github.com/devongovett/rsc-html-stream/blob/1ff7350f280243ee23f7133c26892f9b9065a663/server.js#L15

Can you use `setTimeout` instead?

I'm not sure if we need to wait for a tick, though.

**Comment by devongovett** [comment]
I think it should work. Will have to check what next.js uses again. The delay is necessary to ensure the app shell is flushed before the script tags are added to the stream. That might be the whole page, or maybe not in the case of suspense, but it should always be a valid spot to insert the scripts.

**Comment by devongovett** [comment]
Yeah looks like they use setTimeout when setImmediate isn't available. But I think setTimeout is probably fine in all cases. https://github.com/vercel/next.js/blob/canary/packages/next/src/lib/scheduler.ts#L28

**Comment by devongovett** [comment]
published in 0.0.3
