### ISSUE TITLE
Prevent script tags to corrupt the rendered html

### ISSUE THREAD

**Issue by nestarz** [devongovett/rsc-html-stream#6]
Thanks for your work @devongovett 

I've had no issues with your packages until recently, for some render output the html stream conflict with the added script tags.
Here an example :

<img src="https://<script>(self.__FLIGHT_DATA||=[]).push(](https://url/?url=https%3A%2F%a/%2Fmedias%2Fworks%%22jpe%3Cscript%3E(self.__FLIGHT_DATA||=[]).push()"1:{\"name\":\"C

**Comment by JiangWeixian** [comment]
@devongovett  I have similar question, flight data is push via sync script, if flight data is huge (e.g. more than 1mb). Will it affect dom display? Can we push via async script instead?
